jdbcSettings:
  url: "jdbc:mysql://mysql.cc.puv.fi:3306/e1800960_northwind"
  username: "e1800960"
  password: "Bamena123"
  driverClassName: "com.mysql.jdbc.Driver"

packageName: "fi.vamk.e1800960.northwind.demo.Entity"
